import React,{useState} from 'react';
import { authApi } from '../api/client';
import { Button, ErrorBox } from '../components/UI';

export default function Auth({ onLogin }) {
  const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function submit(e){e.preventDefault();setError('');setLoading(true);try{const r=register?await authApi.register({email,password,fullName}):await authApi.login({email,password});onLogin(r);}catch(err){setError(err.message)}finally{setLoading(false)}}
  return <div className="auth-page"><div className="auth-art"><div className="auth-copy"><span className="eyebrow">A GOLF PERFORMANCE AND CHARITY DRAW PLATFORM</span><h1>Play with purpose.</h1><p>Track your performance, support causes you care about, and stay connected to every draw.</p><div className="auth-points"><span>● Performance tracking</span><span>● Community impact</span><span>● Monthly rewards</span></div></div></div><div className="auth-panel"><div className="auth-mobile-logo">DIGITAL <b>HEROES</b></div><div className="auth-card"><span className="eyebrow">{register?'CREATE ACCOUNT':'WELCOME BACK'}</span><h2>{register?'Join A Golf Performance and Charity Draw Platform':'Your hero hub awaits.'}</h2><p className="muted">{register?'Create your account in a few seconds.':'Sign in to continue to your dashboard.'}</p><ErrorBox message={error}/><form onSubmit={submit}>{register&&<label>Full name<input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name" required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" minLength="8" required/></label><Button loading={loading}>{register?'Create account':'Sign in'}</Button></form><button className="switch-auth" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already have an account? Sign in':'New here? Create an account'}</button></div></div></div>;
}
